---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ip-reconciler
  labels:
    tier: node
    app: whereabouts
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          priorityClassName: "system-node-critical"
          containers:
            - name: whereabouts
              image: ghcr.io/k8snetworkplumbingwg/whereabouts:latest-amd64
              resources:
                requests:
                  cpu: "100m"
                  memory: "50Mi"
              command:
                - /ip-reconciler
                - -kubeconfig=/host/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig
                - -log-level=verbose
              volumeMounts:
                - name: cni-net-dir
                  mountPath: /host/etc/cni/net.d
          volumes:
            - name: cni-net-dir
              hostPath:
                path: /etc/cni/net.d
          restartPolicy: OnFailure
